# Generated by Django 2.2 on 2019-09-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeeditem',
            name='status_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
